name: 'Checkout and Build'
description: 'Checkout code and build project'
inputs:
  targetPlatform:
    description: 'The target platform to build for'
    required: true
  unityVersion:
    description: 'Unity version'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache Library
      uses: actions/cache@v4
      with:
        path: Library
        key: ${{ runner.os }}-${{ inputs.targetPlatform }}-library-${{ hashFiles('**/Library/*') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.targetPlatform }}-library-

    - name: Build Projects
      uses: game-ci/unity-builder@v4
      env:
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        unityVersion: ${{ inputs.unityVersion }}
        targetPlatform: ${{ inputs.targetPlatform }}

    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: Build-${{ inputs.targetPlatform }}
        path: build/${{ inputs.targetPlatform }}
