name: Unity Build

on:
  push:
    branches:
      - main

jobs:
  unity-build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows # Build a Windows standalone.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - WSAPlayer # Build a Windows Store Apps player.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
          - iOS # Build an iOS player.
          - Android # Build an Android .apk standalone app.
          - WebGL # WebGL.
          - PS4 # Build a PS4 standalone.
          - PS5 # Build to PlayStation 5 platform.
          - XboxOne # Build an Xbox One standalone.
          - tvOS # Build a tvOS player.
          - Switch # Build a Nintendo Switch player.
          - VisionOS # Build a visionOS player.

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: ${{ runner.os }}-${{ matrix.targetPlatform }}-library-${{ hashFiles('**/Library/*') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.targetPlatform }}-library-

      - name: Extend Free Disk Space
        if: matrix.targetPlatform == 'Android'
        uses: jlumbroso/free-disk-space@main

      - name: Build Projects
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: '2022.3.20f1'
          targetPlatform: ${{ matrix.targetPlatform }}

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

      - name: Create Deploy Directory
        if: matrix.targetPlatform == 'WebGL'
        run: |
          mkdir deploy

      - name: Copy WebGL Build to Deploy Directory
        if: matrix.targetPlatform == 'WebGL'
        run: |
          cp -R build/WebGL/WebGL/* deploy/

      - name: Copy App Store Privacy Policy to Deploy Directory
        if: matrix.targetPlatform == 'WebGL'
        run : |
          mkdir deploy/AppStore
          cp AppleAppStorePrivacyPolicy.md deploy/AppStore/PrivacyPolicy.md

      - name: Copy Play Store Privacy Policy to Deploy Directory
        if: matrix.targetPlatform == 'WebGL'
        run : |
          mkdir deploy/PlayStore
          cp GooglePlayStorePrivacyPolicy.md deploy/PlayStore/PrivacyPolicy.md

      - name: Deploy to GitHub Pages
        if: matrix.targetPlatform == 'WebGL'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: deploy
          keep_files: true
          enable_jekyll: true
          cname: www.cosmic-voyagers.space
