name: Unity WSA Player Build

on:
  push

jobs:
  build:
    name: Unity Build
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: ${{ runner.os }}-WSAPlayer-library-${{ hashFiles('**/Library/*') }}
          restore-keys: |
            ${{ runner.os }}-WSAPlayer-library-

      - name: Unity Build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: '2022.3.20f1'
          targetPlatform: WSAPlayer

      - run: ls -l build
      - run: ls -l build/WSAPlayer
      - run: ls -l build/WSAPlayer/WSAPlayer


      - name: Visual Studio Build
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe "build/WSAPlayer/WSAPlayer/Cosmic Voyagers.sln"